uuid filter added to logs
browserstack/chitragupta-node pull request #18
Opened 2022-06-24 10:00 UTC by jerry7991

Added the solution for filtering logs with uuid(session_id).

2022-06-24 11:11 UTC, sid888gaur approved these changes

2022-06-24 11:23 UTC, Deepak18-06 approved these changes

2022-06-24 13:32 UTC, mayank2498 commented on lib/chitragupta/chitragupta.js
> +  cls.set('uuid', request.query.uuid);
Add error handling, for request or request.query undefined case.

2022-06-29 11:14 UTC, mayank2498 commented on lib/chitragupta/chitragupta.js
> +      cls.set('uuid', request.body.uuid);
We are already using `setMetaData`.
Is this change required ?

2022-07-07 05:26 UTC, mayank2498 approved these changes

2022-07-12 07:11 UTC, nikhlagrwl requested changes

2022-07-12 07:11 UTC, nikhlagrwl commented on lib/chitragupta/util.js
> +  data.log.uuid = cls.get("uuid") || {};
Let's return a null or empty string rather than empty json as this is a string field.

2022-07-12 07:29 UTC, nikhlagrwl approved these changes

2022-07-12 08:34 UTC, nikhlagrwl requested changes
Please bump the version.

2022-07-13 05:59 UTC, nikhlagrwl approved these changes

2022-07-13 06:02 UTC, merged